### PR TITLE
Ready to Review

### PR DESCRIPTION
**Pull request by htuerker**

### CODE REVIEW

**Comment by talihomz** [comment]
## Good Work, Some few Bugs
---

Hi @nikitin2009 @btuerker. This was a great attempt at the Events app. Was able to sign up, log in and create an event. There are no URL leading to the event pages, so I wasn't sure if this functonality had been implemented.
Got the following error:
events-error
Steps:
1. Create an event.

One last thing: Add a more meaningful README and not the default one.

**Comment by talihomz** [comment]
Hi @nikitin2009 @btuerker. 
Adding events now works well, plus the links at the top of the screen.

There is one major issue remaining. Where is the invites feature? Such that a user can see the events they have been invited to, and respond to these invites? I couldn't test this before since the events feature wasn't working 100%.

**Comment by talihomz** [comment]
## Minor Bug Found :-(
---

Hi @btuerker @nikitin2009. Was able to run the app, created an account, created an event, then this happened.
Screenshot from 2019-04-11 19-54-26

**Comment by talihomz** [comment]
## Invites Working! Found a small Bug
--- 
Great work implementing Invites for this app! I was able to create an event, invite a user and see all invited users for the said event.
I found a bug, and here are the steps to recreate it, plus where I tracked down the problem in the code:

1. I created an event, and invited an arbitrary user.
event-view

2. I clicked on one of the users invited. Instead of navigating to the user's profile, it took to the root page.
event-root-path


After digging through your code, I found that in your `user controller`, you have a method called [correct_user](https://github.com/nikitin2009/private-events/blob/d4d7c354a1f57441f30aa687075ca2d90f8d07dc/app/controllers/users_controller.rb#L40) that is declared as a `before action` for the `show method` [here](https://github.com/nikitin2009/private-events/blob/d4d7c354a1f57441f30aa687075ca2d90f8d07dc/app/controllers/users_controller.rb#L6). By doing this, logged in users cannot view other users profiles.

Other than this minor bug, everything else works fine!

**Comment by htuerker** [comment]
It's not a bug :D It's a feature haha :D 
Screen Shot 2019-04-15 at 2 21 04 PM

**Comment by nikitin2009** [comment]
Haha, just wanted to write this. We don't allow users to see other users profiles.

**Comment by talihomz** [comment]
@nikitin2009 @btuerker hahaha.

Ok. If the user shouldn't see other user profiles, then deactivate the link to their profiles. As it is currently, user will be tempted to click to see the user who is invited.

**Comment by talihomz** [comment]
## Done (Finally! :-))
---

Everything is good now, its a :+1: from me.

**Pull request merged**
